nameOverride: ""
fullnameOverride: ""

image:
  repository: hdns-operator
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

env: production

logLevel: info

numWorkers: 2

ha:
  enabled: true
  leaderElection:
    leaseDurationSeconds: 15
    renewDeadlineSeconds: 10
    retryPeriodSeconds: 2
  replicaCount: 3

monitoring:
  enabled: true
  path: /metrics
  port: 2112
  namespace: monitoring
  interval: 10s
  labels:
    release: monitoring

resources: {}

nodeSelector: {}
