/* AUTO GENERATED CODE */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	dnsblockv1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1"
	versioned "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/clientset/versioned"
	internalinterfaces "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/listers/dnsblock/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DNSBlockInformer provides access to a shared informer and lister for
// DNSBlocks.
type DNSBlockInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DNSBlockLister
}

type dNSBlockInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDNSBlockInformer constructs a new informer for DNSBlock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSBlockInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDNSBlockInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDNSBlockInformer constructs a new informer for DNSBlock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSBlockInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HdnsV1alpha1().DNSBlocks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HdnsV1alpha1().DNSBlocks(namespace).Watch(context.TODO(), options)
			},
		},
		&dnsblockv1alpha1.DNSBlock{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSBlockInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDNSBlockInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dNSBlockInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dnsblockv1alpha1.DNSBlock{}, f.defaultInformer)
}

func (f *dNSBlockInformer) Lister() v1alpha1.DNSBlockLister {
	return v1alpha1.NewDNSBlockLister(f.Informer().GetIndexer())
}
