/* AUTO GENERATED CODE */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DNSBlocks returns a DNSBlockInformer.
	DNSBlocks() DNSBlockInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DNSBlocks returns a DNSBlockInformer.
func (v *version) DNSBlocks() DNSBlockInformer {
	return &dNSBlockInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
