apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: default
spec:
  selector:
    app: webhook-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
