apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hdns-admission-webhook
webhooks:
- name: hdns-admission-webhook.hdns.io
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVQlJ5V281dGFnM0FvRWRaL3UwUkZkVFVpUTU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJME1ETXhOVEUzTWpRd01Gb1hEVEk1TURNeE5ERTNNalF3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0TVo5K2lOalJJVnUKUVFyV1N6RjlmYXd2VHVsN3h5UE4wWThzM2RmL1V6SHpBbXdVRzZJQmYrZlZhbjF3NzBPUnpCWGF2MUhRVmV1aQpSbnRpeXgzSXNZeURoVTJ1R09MZjVVNjFld2tmZHBTcTNRQ3RDMkNoa1FVMm1jUEFuQ1JudFpwWVpwMWtZZXhmCjI2anZYQXdvOHhiVTBRTnFPWFdGZmt6Y3Qzeis3Zjd1eHpDV0t5ZzcvS1o1VW8yRXh6dWNLSXRtZVQ0dW1zMWsKYTFucWYzZkN1SnpTb3RYcmdNbExpUmZsam5vN0IzcHN2UGpCZFN4NDc3cndnTmo2UGdwRDFMUW1heGU5QlYzMQp3Q2pGUWR4cWtCbHVFbXFnMHBiWnZpVytoTWJSRk5VeDVvTnRoQ3ZQbGN1Q3R4aE01QU5CUDdpbG0yRmNIY2lWCkMreXF1Q1hJNndJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFqQWRCZ05WSFE0RUZnUVVqeisxaExwSkVZMUVDa3JkenJ4ZkpHWUVUczh3SHdZRFZSMGpCQmd3Rm9BVQpqeisxaExwSkVZMUVDa3JkenJ4ZkpHWUVUczh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVxVGNVRnpXVWU5ClBQTGlIUDRXQnNyZ0d0Y3MzOW1mVDVtRVExZ00xQjJiSkUwUDNuN0RuT3A1VEJ2NjIrUHgyQzVBcWVUaGpUQngKZ0hFbWxnVTVoRlljQUd6ck5OZjlvQ0pWR1FzYTRnSndiaXh4YXVXOTZiZCtEZWFIRHFZRkVVQ0hESDg2NnFETgpCYVZudEd4U2dqa0ZGTXp0S0tYSWFGR2Q4RVgxWGRGREVUTzZRRXRnTUk5Qk5IYU1qTkxRSVpYc1dFOXlIRW51Cko0VGNPUTI0bWtoYnhLU1VhcUdEdGE3OHNnMmE4WGdLYW1qZ3Bhc3dTd09jNTB5RG5scWpudm5wSjdOZHNuMEQKR1BCUGZEakNKbEwveEVSU3FjMXRSTmZQSTFDN3ZDVUtsYmY3M0R4UlN3bUJydDdHdlQyRi9DU0lkQ29JVlNGZAp6ZHhGQzFTaGt4Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      namespace: default
      name: webhook-service
      path: /mutate
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5