/* AUTO GENERATED CODE */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/clientset/versioned/typed/dnsblock/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHdnsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHdnsV1alpha1) DNSBlocks(namespace string) v1alpha1.DNSBlockInterface {
	return &FakeDNSBlocks{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHdnsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
