apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: hdns
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.webhook.targetPort }}
  selector:
    app: webhook-server
