/* AUTO GENERATED CODE */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1"
	dnsblockv1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/applyconfiguration/dnsblock/v1alpha1"
	scheme "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSBlocksGetter has a method to return a DNSBlockInterface.
// A group's client should implement this interface.
type DNSBlocksGetter interface {
	DNSBlocks(namespace string) DNSBlockInterface
}

// DNSBlockInterface has methods to work with DNSBlock resources.
type DNSBlockInterface interface {
	Create(ctx context.Context, dNSBlock *v1alpha1.DNSBlock, opts v1.CreateOptions) (*v1alpha1.DNSBlock, error)
	Update(ctx context.Context, dNSBlock *v1alpha1.DNSBlock, opts v1.UpdateOptions) (*v1alpha1.DNSBlock, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DNSBlock, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DNSBlockList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSBlock, err error)
	Apply(ctx context.Context, dNSBlock *dnsblockv1alpha1.DNSBlockApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DNSBlock, err error)
	DNSBlockExpansion
}

// dNSBlocks implements DNSBlockInterface
type dNSBlocks struct {
	client rest.Interface
	ns     string
}

// newDNSBlocks returns a DNSBlocks
func newDNSBlocks(c *HdnsV1alpha1Client, namespace string) *dNSBlocks {
	return &dNSBlocks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dNSBlock, and returns the corresponding dNSBlock object, and an error if there is any.
func (c *dNSBlocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DNSBlock, err error) {
	result = &v1alpha1.DNSBlock{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsblocks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSBlocks that match those selectors.
func (c *dNSBlocks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DNSBlockList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DNSBlockList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSBlocks.
func (c *dNSBlocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dNSBlock and creates it.  Returns the server's representation of the dNSBlock, and an error, if there is any.
func (c *dNSBlocks) Create(ctx context.Context, dNSBlock *v1alpha1.DNSBlock, opts v1.CreateOptions) (result *v1alpha1.DNSBlock, err error) {
	result = &v1alpha1.DNSBlock{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSBlock).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dNSBlock and updates it. Returns the server's representation of the dNSBlock, and an error, if there is any.
func (c *dNSBlocks) Update(ctx context.Context, dNSBlock *v1alpha1.DNSBlock, opts v1.UpdateOptions) (result *v1alpha1.DNSBlock, err error) {
	result = &v1alpha1.DNSBlock{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsblocks").
		Name(dNSBlock.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSBlock).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dNSBlock and deletes it. Returns an error if one occurs.
func (c *dNSBlocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsblocks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSBlocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsblocks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dNSBlock.
func (c *dNSBlocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSBlock, err error) {
	result = &v1alpha1.DNSBlock{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsblocks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dNSBlock.
func (c *dNSBlocks) Apply(ctx context.Context, dNSBlock *dnsblockv1alpha1.DNSBlockApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DNSBlock, err error) {
	if dNSBlock == nil {
		return nil, fmt.Errorf("dNSBlock provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dNSBlock)
	if err != nil {
		return nil, err
	}
	name := dNSBlock.Name
	if name == nil {
		return nil, fmt.Errorf("dNSBlock.Name must be provided to Apply")
	}
	result = &v1alpha1.DNSBlock{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("dnsblocks").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
