/* AUTO GENERATED CODE */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DNSBlockListerExpansion allows custom methods to be added to
// DNSBlockLister.
type DNSBlockListerExpansion interface{}

// DNSBlockNamespaceListerExpansion allows custom methods to be added to
// DNSBlockNamespaceLister.
type DNSBlockNamespaceListerExpansion interface{}
