/* AUTO GENERATED CODE */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1"
	dnsblockv1alpha1 "github.com/hamedetemaad/hdns-operator/pkg/dnsblock/v1alpha1/apis/applyconfiguration/dnsblock/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=hdns.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("DNSBlock"):
		return &dnsblockv1alpha1.DNSBlockApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSBlockSpec"):
		return &dnsblockv1alpha1.DNSBlockSpecApplyConfiguration{}

	}
	return nil
}
