/* AUTO GENERATED CODE */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DNSBlockSpecApplyConfiguration represents an declarative configuration of the DNSBlockSpec type for use
// with apply.
type DNSBlockSpecApplyConfiguration struct {
	Domains []string `json:"domains,omitempty"`
}

// DNSBlockSpecApplyConfiguration constructs an declarative configuration of the DNSBlockSpec type for use with
// apply.
func DNSBlockSpec() *DNSBlockSpecApplyConfiguration {
	return &DNSBlockSpecApplyConfiguration{}
}

// WithDomains adds the given value to the Domains field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Domains field.
func (b *DNSBlockSpecApplyConfiguration) WithDomains(values ...string) *DNSBlockSpecApplyConfiguration {
	for i := range values {
		b.Domains = append(b.Domains, values[i])
	}
	return b
}
